apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: golem
  labels:
    app: golem
spec:
  selector:
    matchLabels:
      app: golem
  template:
    metadata:
      labels:
        app: golem
    spec:
      containers:
      - name: golem
        image: golemfactory/golem
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
          - mountPath: /data
            name: golem-data
      volumes:
        - name: golem-data
          emptyDir: {}
      restartPolicy: Always
